---
name: Test

on:
  pull_request:
  push:
    branches: [main, develop, issue-*]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy, llvm-tools-preview

      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest

      - name: Run tests with coverage
        run: cargo llvm-cov nextest

      - name: Execute the program
        run: |
          mkdir output
          time cargo run ./output/mandelbrot_1024x1024.png 1024x1024 -2.0,2.00 2.0,-2.0

      - name: Upload resulting image
        uses: actions/upload-artifact@v3
        with:
          name: "mandelbrot_1024x1024.png"
          path: "./output/mandelbrot_1024x1024.png"
